FROM python:3.9-slim

WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir -r requirements.txt

# ✅ Install mysql client for `mysqladmin`
RUN apt-get update && apt-get install -y default-mysql-client && rm -rf /var/lib/apt/lists/*

# Copy wait script
COPY . .
COPY wait-for-db.sh /wait-for-db.sh
RUN chmod +x /wait-for-db.sh


CMD ["/bin/bash", "/wait-for-db.sh", "db", "uvicorn", "app:app", "--host", "0.0.0.0", "--port", "8000"]
